# Generated by Django 4.1.3 on 2022-11-14 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saber11.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('codinst', models.CharField(blank=True, max_length=20, null=True)),
                ('calendario', models.CharField(blank=True, choices=[('A', 'calendario A'), ('B', 'calendario B'), ('O', 'Otro')], max_length=2, null=True)),
                ('naturaleza', models.CharField(blank=True, choices=[('OFICIAL', 'oficial'), ('NO OFICIAL', 'no oficial')], max_length=12, null=True)),
                ('evaluados', models.IntegerField(blank=True, null=True)),
                ('matematicas', models.FloatField(blank=True, null=True)),
                ('sociales', models.FloatField(blank=True, null=True)),
                ('ingles', models.FloatField(blank=True, null=True)),
                ('ciencias', models.FloatField(blank=True, null=True)),
                ('lectura', models.FloatField(blank=True, null=True)),
                ('jornada', models.CharField(blank=True, choices=[('MAÑANA', 'mañana'), ('TARDE', 'tarde'), ('NOCTURNA', 'nocturna'), ('FIN DE SEMANA', 'fin de semana'), ('ÚNICA', 'única'), ('COMPLETA', 'completa')], max_length=20, null=True)),
                ('periodo', models.CharField(blank=True, max_length=6, null=True)),
                ('promponderado', models.FloatField(blank=True, null=True)),
                ('puntajeglobal', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saber11.municipio')),
            ],
        ),
    ]
