# Generated by Django 4.1.3 on 2022-12-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icfesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcionestandar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='icfesapp'),
        ),
        migrations.AlterField(
            model_name='preguntaestandar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='icfesapp'),
        ),
    ]
