# Generated by Django 4.1.3 on 2022-11-10 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, choices=[('ciencias', 'ciencias'), ('matematicas', 'matematicas'), ('lectura', 'lectura'), ('ingles', 'ingles'), ('sociales', 'sociales')], default='ciencias', max_length=12, null=True)),
                ('contexto', models.TextField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('explicacion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media')),
                ('respuestas_tienen_imagen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('ciencias', 'ciencias'), ('matematicas', 'matematicas'), ('lectura', 'lectura'), ('ingles', 'ingles'), ('sociales', 'sociales')], default='ciencias', max_length=12)),
                ('publicado', models.DateTimeField(blank=True, null=True)),
                ('fecha_agregado', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificado', models.DateTimeField(default=django.utils.timezone.now)),
                ('preguntas', models.ManyToManyField(to='preicfesapp.pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='opciones',
            field=models.ManyToManyField(to='preicfesapp.respuestamultiple'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='respuesta_correcta',
            field=models.ManyToManyField(blank=True, related_name='correcta', to='preicfesapp.respuestamultiple'),
        ),
    ]
