# Generated by Django 4.1.3 on 2022-11-10 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preicfesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'quizzes'},
        ),
    ]
