# Generated by Django 4.1.3 on 2022-11-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preicfesapp', '0002_alter_quiz_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuestamultiple',
            options={'verbose_name_plural': 'Respuestas múltiples'},
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='explicacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
