# Generated by Django 4.1.3 on 2022-11-13 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preicfesapp', '0003_alter_respuestamultiple_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media')),
                ('es_correcta', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='opciones',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respuesta_correcta',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='preguntas',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='quiz',
            field=models.ManyToManyField(to='preicfesapp.quiz'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='categoria',
            field=models.CharField(blank=True, choices=[('ciencias', 'Ciencias naturales'), ('matematicas', 'Matemáticas'), ('lectura', 'Lectura crítica'), ('ingles', 'Inglés'), ('sociales', 'Sociales y ciudadanas')], default='ciencias', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='categoria',
            field=models.CharField(choices=[('ciencias', 'Ciencias naturales'), ('matematicas', 'Matemáticas'), ('lectura', 'Lectura crítica'), ('ingles', 'Inglés'), ('sociales', 'Sociales y ciudadanas')], default='ciencias', max_length=12),
        ),
        migrations.DeleteModel(
            name='RespuestaMultiple',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preicfesapp.pregunta'),
        ),
    ]
