# Generated by Django 4.1.3 on 2022-12-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preicfesapp', '0006_lectura_preguntalectura'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='titulo',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
