# Generated by Django 4.1.3 on 2022-12-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preicfesapp', '0007_lectura_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preicfesapp.quiz'),
        ),
    ]
